# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

# Optionally build your docs in additional formats such as PDF
formats:
  - pdf
  - epub

python:
  version: 3.8
  install:
    - requirements: docs/requirements.txt
    - path: .
